### ISSUE TITLE
uart2_vprintf and uart3_vprintf in libwwg uartlib.c use uart1_putc

### ISSUE THREAD

**Issue by MatthewMckayDavies** [ve3wwg/stm32f103c8t6#16]
Great book!

I'm following the book on a ST Nucleo board without USB, so for the winbond program I switched to uart2 for the std device. After a bit of head scratching I spotted a bug in the uartlib.c, patch below:

diff` --git a/rtos/libwwg/src/uartlib.c b/rtos/libwwg/src/uartlib.c
index f9e8f4c..ce8d3eb 100644
--- a/rtos/libwwg/src/uartlib.c
+++ b/rtos/libwwg/src/uartlib.c
@@ -440,7 +440,7 @@
 
 int
 uart2_vprintf(const char *format,va_list ap) {
\-	return mini_vprintf_cooked(uart1_putc,format,ap);
\+	return mini_vprintf_cooked(uart2_putc,format,ap);
 }
 
 int
@@ -497,7 +497,7 @@
 
 int
 uart3_vprintf(const char *format,va_list ap) {
\-	return mini_vprintf_cooked(uart1_putc,format,ap);
\+	return mini_vprintf_cooked(uart3_putc,format,ap);
 }
 
 int

**Comment by ve3wwg** [comment]
Thank you, the fix has been applied.
