### ISSUE TITLE
The RTC, the alarm flag and the overflow flag

### ISSUE THREAD

**Issue by fivdi** [ve3wwg/stm32f103c8t6#18]
Chapter 10, Real-Time Clock (RTC), page 181, states the following:

> It appears that the alarm flag is always set when an overflow happens, whether there was an alarm pending or not. As far as I can tell this is one of those undocumented features.

I don't believe this to be the case. The reset value for the RTC alarm register (RTC_ALR) is 0xFFFFFFFF. If the value of the RTC alarm register is not modified, the alarm and overflow flags will actually be set at the same time making it appear as if the alarm flag is set when an overflow happens. If the RTC alarm register is set to any value other than 0xFFFFFFFF the alarm and overflow flags will be set at different times.

The following text is taken from the STM32F103xx reference manual:

>The RTC Overflow flag (OWF) is asserted on the last RTC Core clock cycle before the
counter reaches 0x0000.

>The RTC_Alarm and RTC Alarm flag (ALRF) (see Figure 180) are asserted on the last RTC
Core clock cycle before the counter reaches the RTC Alarm value stored in the Alarm
register increased by one (RTC_ALR + 1).

In the rtc example in chapter 10, the overflow and alarm flags are set at the same time because the RTC alarm register has it's reset value of 0xFFFFFFFF, unless of course the user presses the 'A' key resulting in the value of the RTC alarm register being set to a value other than 0xFFFFFFFF.

**Comment by ve3wwg** [comment]
Alright, but I think I'll leave that code as is since the text has described it in print. I'll keep this note for future reference so that the chapter can be revised if it goes to a second edition.
