### ISSUE TITLE
Can't get the libopencm3

### ISSUE THREAD

**Issue by ivand58** [ve3wwg/stm32f103c8t6#3]
A problem with the submodule:

     fatal: reference is not a tree: 0862b1f75640c819aaae99052db05e8fd7021c56
     Unable to checkout '0862b1f75640c819aaae99052db05e8fd7021c56' in submodule path 'libopencm3'

**Comment by ve3wwg** [comment]
You can manually check it out directly to the subdirectory, or use the --recursive option:
